#!/usr/bin/env node

var Q = require('bluebird'),
  ReplicaSet = require('./').ReplicaSet;


var rs = new ReplicaSet();


rs.start()
  .then(function() {
    console.log('>>>> Replica set ready');
  })
  .catch(function(err) {
    console.error(err);

    console.log('>>>> Stopping replica set');

    return rs.stop();
  });
